FROM node:16.17

ARG NUXT_APP_BASE_URL
ENV NUXT_APP_BASE_URL=${NUXT_APP_BASE_URL}

ARG NUXT_APP_SENTRY_DSN
ENV NUXT_APP_SENTRY_DSN=${NUXT_APP_SENTRY_DSN}

EXPOSE 3000
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# RUN npm run build
CMD [ "npm", "run", "dev" ]
