FROM node:14.18.3-slim

ARG VUE_APP_API_BASE_URL
ENV VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}

ARG VUE_APP_SENTRY_DSN
ENV VUE_APP_SENTRY_DSN=${VUE_APP_SENTRY_DSN}

WORKDIR /app
COPY . ./

RUN npm install
RUN npm run build
